### ISSUE TITLE
兼容ItemsAdder！

### ISSUE THREAD

**Issue by EggFine** [xMikux/Slimefun-Resourcepack#11]
**Describe about this feature request.**
A clear introduction to what you want (addons texture, some not implement items textures)

在资源包加入ItemsAdder时，ItemsAdder的默认包纹理就会替换掉，请添加对ItemsAdder默认包的兼容性，谢谢！:p

在資源包加入ItemsAdder時，ItemsAdder的默認包紋理就會替換掉，請添加對ItemsAdder默認包的相容性，謝謝！:p

**Please note this resourcepack only remake & combined from other resourcepack, so is hard to add new texture (because the author not the artist).**

**Comment by xMikux** [comment]
![image](https://user-images.githubusercontent.com/26039249/185742339-484d73b4-1a5f-48aa-8eb8-2889bf0c9d89.png)

我測試 DefaultPack 與 OtherPack 一起安裝沒有會被覆蓋的問題

請問是哪裡有被覆蓋到

**Comment by EggFine** [comment]
稍等，我去進行測試並截圖給您

**Comment by EggFine** [comment]
![image](https://user-images.githubusercontent.com/34890548/185742594-04a08b45-8cec-43f4-958b-08ccde48d562.png)
僅使用了ItemsAdder默認包

**Comment by xMikux** [comment]
你有 /iazip 過嗎?

**Comment by EggFine** [comment]
有的

**Comment by xMikux** [comment]
可以把 data 的資料夾壓縮一份上傳過來嘛
因為預設情況下應該是正常可使用的

**Comment by EggFine** [comment]
好的

**Comment by EggFine** [comment]
[data_2.zip](https://github.com/xMikux/Slimefun-Resourcepack/files/9386906/data_2.zip)
抱歉，github不支持7z，又壓縮了一遍

**Comment by xMikux** [comment]
沒關係 我測試看看差別在哪

**Comment by EggFine** [comment]
將本材質包去除便恢復正常，粘液科技的材質是沒問題的，只有ia的物品出現此問題

**Comment by EggFine** [comment]
有頭緒嗎(ง •_•)ง

**Comment by xMikux** [comment]
我仍然在測試

**Comment by xMikux** [comment]
![image](https://user-images.githubusercontent.com/26039249/185742955-99af6724-e9e2-4d9f-8300-a532e0576f6d.png)
它不太想讓我壓縮

**Comment by EggFine** [comment]
啊！？

**Comment by EggFine** [comment]
我壓縮的時候是沒有問題的呀

**Comment by EggFine** [comment]
(´･ω･`)?

**Comment by xMikux** [comment]
你確定你的 DefaultPack 沒有損壞嘛 看起來似乎有一點損壞

**Comment by xMikux** [comment]
![image](https://user-images.githubusercontent.com/26039249/185743007-f6e5b607-d5a1-4f5b-829c-8e36f6ecee6e.png)

**Comment by xMikux** [comment]
失敗壓縮完會是長這樣

**Comment by EggFine** [comment]
我確定呀，因為删掉這個材質包就恢復正常了

**Comment by EggFine** [comment]
![image](https://user-images.githubusercontent.com/34890548/185743022-ac2b7671-bb4b-4828-8f8a-be4678e165bb.png)

**Comment by EggFine** [comment]
我可以使用您的data檔案試試嗎

**Comment by xMikux** [comment]
可以 稍等我一下

**Comment by EggFine** [comment]
幸苦啦o(*￣▽￣*)ブ

**Comment by xMikux** [comment]
[data.zip](https://github.com/xMikux/Slimefun-Resourcepack/files/9386936/data.zip)

下次如果有關於材質包的使用問題，也許可以在 Discord 找我

**Comment by EggFine** [comment]
好的，请问您的Discord？

**Comment by xMikux** [comment]
https://discord.gg/GF4CwjFXT9

**Comment by xMikux** [comment]
我之後會在專案的 Readme 也添加上 Discord 的邀請連結 方便這種長的安裝問題可以直接在頻道中一起討論

**Comment by EggFine** [comment]
![image](https://user-images.githubusercontent.com/34890548/185743349-0030ee89-cce9-4da2-a4c9-4c3932de30a7.png)
我加入不了，點擊接受會跳轉到這裡

**Comment by xMikux** [comment]
我看你成功加入了耶

**Comment by EggFine** [comment]
哎？？？好吧！我去主页看一看

**Comment by xMikux** [comment]
會有一個叫做 ``Slimefun 繁體中文版`` 的伺服器

**Comment by EggFine** [comment]
好的，我需要等待十分鐘才可以發言

**Comment by EggFine** [comment]
我使用您的data包生成的資源包用戶端裝載後會閃退

**Comment by xMikux** [comment]
目前沒有打算獨立出一個專門的伺服器用材質包 因為使用人數不多且沒有會畫畫的可以幫忙將缺失的材質補齊

然後你有使用我上傳的 data.zip 進行安裝嘛

是正常的還是仍然缺失材質

**Comment by EggFine** [comment]
QAQ

**Comment by xMikux** [comment]
hmm

**Comment by xMikux** [comment]
macos ?

**Comment by EggFine** [comment]
Windows 11

**Comment by xMikux** [comment]
好吧 這很奇怪 
閃退的時候它是寫 render error 嘛

**Comment by EggFine** [comment]
我删除了無用的Slimefun Addon資源包，現在可以裝載了

**Comment by EggFine** [comment]
可以說正常了但沒有完全正常

**Comment by EggFine** [comment]
![image](https://user-images.githubusercontent.com/34890548/185743582-57cbdd5b-58b1-40ef-8ba6-53a475e2b8ee.png)

**Comment by xMikux** [comment]
看起來好像是正常的?
畢竟 Slimefun 的物品並不會顯示在列表中
我沒有製作單一列表在 IA 內

**Comment by EggFine** [comment]
GUI不正常

**Comment by EggFine** [comment]
![image](https://user-images.githubusercontent.com/34890548/185743649-4ac88bd1-22f9-4ecf-a574-1ddf170692c7.png)

**Comment by xMikux** [comment]
喔 好像 GUI 歪掉了
我嘗試做一個乾淨的安裝 在裝一次看看

**Comment by EggFine** [comment]
好的，麻煩了

**Comment by EggFine** [comment]
我可以在Discord中发言了

**Comment by xMikux** [comment]
在 Discord 中討論吧 畢竟這邊有一點延遲

**Comment by xMikux** [comment]
問題已解決！
