### ISSUE TITLE
Leather textures on character are broken

### ISSUE THREAD

**Issue by rackgaming** [xMikux/Slimefun-Resourcepack#12]
**Describe about this feature request.**
I give people leather upon joining my server for protection due to real seasons so I was curious if you could fix leather armor to show appropriately like the others.

**Please note this resourcepack only remake & combined from other resourcepack, so is hard to add new texture (because the author not the artist).**

**Comment by xMikux** [comment]
I will fix it later! Thanks the report.

**Comment by xMikux** [comment]
Hi, it is now fixed. You can download from [Beta Pack](https://github.com/xMikux/Slimefun-Resourcepack/releases/tag/latest).

**Comment by rackgaming** [comment]
Ok so I need your help on how to fix this, on joining when they receive the starter kit, the texture doesn't apply.

**Comment by rackgaming** [comment]
![image](https://user-images.githubusercontent.com/7550358/206708898-f10f1251-692f-40ca-b495-e331add12e6d.png)
Here is the slimefun guide when giving from essentials kits, it shows like a basic slimefun guidebook but when doing /sf guide this is what is given.
![image](https://user-images.githubusercontent.com/7550358/206709045-38a005cb-5175-4d08-aaf5-ce5391d50010.png)

**Comment by xMikux** [comment]
maybe, the kit inside is an old slimefun guide? (may contain old nbt data without any texture nbt)

**Comment by rackgaming** [comment]
which is not a big deal but I can tell them to get the book manually. it just disables the main book.

**Comment by rackgaming** [comment]
No I have tried making the kit with the new one and it should replace that old slimefun book.

**Comment by rackgaming** [comment]
ofcourse i dont have itemsadder so maybe

**Comment by xMikux** [comment]
Actually, I didn't use essentials, so I am not sure about it.
But it seems like, The plugin it self eat some nbt data, so texture is gone.

**Comment by xMikux** [comment]
> ofcourse i dont have itemsadder so maybe

The resourcepack should work without ItemsAdder

**Comment by rackgaming** [comment]
It seems like it does because looking in the kits yml there is no custom NBT data just basic words. 
![image](https://user-images.githubusercontent.com/7550358/206710496-4e85bdc6-4b97-4fe5-a79b-6a9fe503259f.png)

**Comment by xMikux** [comment]
Yep, it should contain more data like this
![image](https://user-images.githubusercontent.com/26039249/206711207-4f9caba5-a32a-4404-95aa-fe7eff0308e0.png)

``CustomModelData`` vaule is how the resourcepack find the texture to apply.

**Comment by xMikux** [comment]
so maybe need to find better kits plugins to replace essentials one.

**Comment by rackgaming** [comment]
I will try PlayerKits and get back to you so maybe somewhere you can add like "This does not work with essential kits so you must use a plugin like PlayerKits to have the guidebook work and show correctly

**Comment by rackgaming** [comment]
Ok so I found the fix in essentials config.yml they need this 
![image](https://user-images.githubusercontent.com/7550358/206718168-8147487e-f5d9-4a5d-8941-0166d9499f3e.png)

**Comment by xMikux** [comment]
👍
