### ISSUE TITLE
Redstone Black & Pink textures

### ISSUE THREAD

**Issue by rackgaming** [xMikux/Slimefun-Resourcepack#13]
**Describe the problem:**

Redstone is black and pink

**Screenshots:**
![image](https://user-images.githubusercontent.com/7550358/207010743-2df4ec62-579a-4089-a189-c76a933c9f33.png)

**Version Info:**

(Please click after you create the issues)

- Resourcepack Version:
 V1.0.10
- Minecraft Version:
1.19.2
Mod:
Fabric
Sodium & Iris 1.19.2

**Comment by rackgaming** [comment]
Also it doesn't seem the server side resource pack downloads onto forge clients. I joined my server and it didn't download the server side resource pack.

**Comment by rackgaming** [comment]
Forge 43.2.0

**Comment by xMikux** [comment]
I tested it, it works normally.

**Comment by xMikux** [comment]
> Also it doesn't seem the server side resource pack downloads onto forge clients. I joined my server and it didn't download the server side resource pack.

Maybe your mods or something blocked resourcepack load.
If you can use vanilla to load server resourcepack.

**Comment by xMikux** [comment]
> I tested it, it works normally.

I see you are using another resourcepack, I am not sure if that caused it.

**Comment by rackgaming** [comment]
I have used these resource packs in combination on regular client, no affect.

**Comment by xMikux** [comment]
So, when using modded client, it will buggy?

**Comment by rackgaming** [comment]
when using a modded client, the redstone placed on ground is the only texture missing.

**Comment by xMikux** [comment]
Yeah, then we need your mod list and resourcepack to see if I can reproduce this bug.

**Comment by rackgaming** [comment]
I already told you my mod list under the original post Fabric API, Iris and sodium are the mods.

**Comment by rackgaming** [comment]
But iris and sodium install onto the minecraft launcher as their own loader and don't use the original folders for the mods.

**Comment by rackgaming** [comment]
the resource pack is RT legendary texture pack 512

**Comment by xMikux** [comment]
![image](https://user-images.githubusercontent.com/26039249/208455867-2a3cf4c2-d797-4919-b810-41ccd31bc0da.png)
![image](https://user-images.githubusercontent.com/26039249/208456277-ce3b2ee6-36cd-4184-80e7-df2ec3770f79.png)
Looks normal
