### ISSUE TITLE
Support for 1.19.3

### ISSUE THREAD

**Issue by Filosofas154** [xMikux/Slimefun-Resourcepack#14]
On the new Minecraft 1.19.3, they changed how I saw the resource pack structure and now it needs an update. I would love to see this resource pack updated to 1.19.3!

p.s I am very happy to see this wonderful slimefun resource pack and what pleases me most is that it is still not an abandoned project! Keep it up!

**Comment by xMikux** [comment]
Hi, thanks for your support!

It seems like ItemAdders did not upgrade to 1.19.3, so I can't start to update this.

When the plugin is updated, I will start to look at what I need to change.

**Comment by xMikux** [comment]
Hi, now support 1.19.3 and below versions. (2598262)
You can check if everything is working properly!

**Comment by Filosofas154** [comment]
Thank you and merry Christmas!
Everything is working perfectly!
