### ISSUE TITLE
Black and pink missing texture on 1.19.3

### ISSUE THREAD

**Issue by mio9** [xMikux/Slimefun-Resourcepack#15]
**Describe the problem:**

Basically all items becomes black and pink missing texture. Happens only on 1.19.3, 

**Screenshots:**

Slimefun guide in 1.19.3
![javaw_I3JlSpLTes](https://user-images.githubusercontent.com/11581624/212562174-0d86d6df-e681-4c19-b4c2-073be9a607d2.png)

Slimefun guide in 1.19.1 and 1.19.2
![image](https://user-images.githubusercontent.com/11581624/212562210-a844640f-a98f-4001-9957-c18aa16c37d9.png)

**Version Info:**

Problem persists in 1.19.3

- Resourcepack Version:
  (Pleases write the verison)
- Minecraft Version:
  -  [x] 1.19.3
  - [ ] 1.18
  - [ ] 1.17
  - [ ] 1.16
  - [ ] 1.15
  - [ ] 1.14
- CIT Mod:
  - [ ] Optifine
  - [ ] CIT Resewn

**Comment by xMikux** [comment]
Hi, have you tried [Beta Pack](https://github.com/xMikux/Slimefun-Resourcepack/releases/tag/latest)?
It should fix in beta, release version still can't show correct texture (v1.0.10 for 1.19.2)

**Comment by xMikux** [comment]
I will release a new version for this, to make sure it won't confuse others.

**Comment by roracle** [comment]
I don't mean to dr frankenstein this post, but does the current release operate with 1.19.3? i've been having a heck of a time with my repo, and we're all (the Slimefun Repainted group) trying to figure this out.

**Comment by xMikux** [comment]
![image](https://user-images.githubusercontent.com/26039249/216397217-8493bc59-11f2-484f-a7eb-79788e9f4b76.png)
![image](https://user-images.githubusercontent.com/26039249/216397308-ca452b0f-c6f8-4b66-b624-6f6e8d33b814.png)

**Comment by roracle** [comment]
Okay the instructions say to use itemadder, but that's a premium plugin, unless I'm looking at the wrong one. 

Traditionally, one just puts the item-models.yml in the ./plugins/slimefun directory but your instructions are different.

**Comment by xMikux** [comment]
Yeah, ItemAdder is a premium plugin, unless you want to generate the pack.
Normally, player just need to download ``Slimefun-ResourcePack.zip``, and load it on their client.
And server admin put ``item-models.yml`` into ./plugins/Slimefun to overwrite current one.

**Comment by xMikux** [comment]
ItemsAdder is not required to install, all things should work fine without this plugin.

**Comment by roracle** [comment]
I see where you say to do it the way I mentioned now. But I'm getting no function from right-clicking with the guide in hand, I have to use` /sf open_guide` to even see anything. The guide has no texture, and under "Tools" some of those items are purple/black checker squares. My normal enchanted diamond pick is also a purple/black squares as well.

**Comment by xMikux** [comment]
take a new book with ``/sf guide``

**Comment by roracle** [comment]
That worked for the guide, but those items I mentioned are still purple/black, including my vanilla enchanted diamond pick.

**Comment by roracle** [comment]
![Screenshot from 2023-02-02 11-40-12](https://user-images.githubusercontent.com/9681146/216400921-9d4f7c81-e82f-4e0a-a5ce-88068ab53032.png)

**Comment by xMikux** [comment]
for existing item, seem like, your server already has a custom item-model id before.
So, it doesn't match this new id.

**Comment by xMikux** [comment]
but it's weird to see there have not texture on the guide.

**Comment by xMikux** [comment]
![image](https://user-images.githubusercontent.com/26039249/216401287-ed69b1f3-c92d-4871-b24e-fa8fd10ba5ec.png)

**Comment by roracle** [comment]
i did put in the one from raulh22.
also that screenshot was before getting a new guide. the new one has the texture

**Comment by xMikux** [comment]
yeah, so all texture work fine now?

**Comment by roracle** [comment]
no... Let me elaborate:
I was using the item-models.yml from RaulH22, to no avail.
I found this github today and asked if it was working with 1.19.3, you said it was, I gave you a thumbs up.
Next, I stopped the server, installed your item-models.yml then started the server back up.
Logged in on my PC, installed your pack, and this conversation continued to this point.

**Comment by xMikux** [comment]
because this pack remake the RaulH22, so you need to replace [item-models.yml](https://github.com/xMikux/Slimefun-Resourcepack/releases/download/v1.0.11/item-models.yml)

**Comment by roracle** [comment]
Above I said:
>Next, I stopped the server, installed your item-models.yml then started the server back up. Logged in on my PC, installed your pack, and this conversation continued to this point.

**Comment by xMikux** [comment]
weird, I am not sure what it causes.

I will test on vanilla client to see the tool page.

**Comment by roracle** [comment]
> weird, I am not sure what it causes.
> 
> I will test on vanilla client to see the tool page.

I'm actually on Optifine preview client. Should I try in vanilla?

**Comment by xMikux** [comment]
Optifine weird

**Comment by roracle** [comment]
Update: after launching Optifine again, it's working. Maybe it was a cache problem.
