### ISSUE TITLE
我使用的最新版本，机器不显示材质

### ISSUE THREAD

**Issue by cat-catmiao** [xMikux/Slimefun-Resourcepack#16]
我使用的是最新的材质包设定，按照教程设置好了，但是只显示物品材质，机器放下后不会有材质
![image](https://user-images.githubusercontent.com/83876597/212794508-6f1bd9af-0c2f-4b03-a8b8-d364a9b954ca.png)

- Resourcepack Version:
 v1.0.10
- Minecraft Version:
  - [ ] 1.19.3
- CIT Mod:
  - [ ] CIT Resewn

**Comment by xMikux** [comment]
機器本身不支援方塊顯示喔
本資源包 包括其他的 都是只支援手上物品圖案顯示 但沒有在世界上的方塊顯示

**Comment by mio9** [comment]
想知道你看著什麼機器的話，可以在伺服器安裝這個插件
https://github.com/SchnTgaiSpock/SlimeHUD

**Comment by xMikux** [comment]
由於太長時間沒有任何回覆，這個問題將會被關掉
