### ISSUE TITLE
Compatibility with Magic

### ISSUE THREAD

**Issue by MrRaposinha** [xMikux/Slimefun-Resourcepack#17]
Make the Slimefun's resourcepack compatible with the [Magic](https://www.spigotmc.org/resources/magic.1056/)'s resourcepack, both together conflict with eachother.

**Comment by xMikux** [comment]
Hi, you need to combine (merge) these two packs together by yourself, using ItemAdder this plugin.
I can't by default include Magic resourcepack in Slimefun resourcepack, because is not relevant.
I can provide my pre generate pack to you if you need it.

**Comment by xMikux** [comment]
Hi, because this issue is no longer active, it will close soon.

If you need a pre-generated pack, please reply to this message thanks!

**Comment by MrRaposinha** [comment]
> Hi, because this issue is no longer active, it will close soon.
> 
> If you need a pre-generated pack, please reply to this message thanks!

Hi, sorry for the late response, I used ItemsAdder to combine them, whoever, both packs uses the same item model ID for some items, and this makes a mess with both the textures.

**Comment by MrRaposinha** [comment]
> Hi, I don't know Magic plugins resourcepack their model ID ranges, so not sure where the conflict is.
> 
> Here is a pre-generated pack, you can try it. [generated.zip](https://github.com/xMikux/Slimefun-Resourcepack/files/10708338/generated.zip)

Thanks! It seems that it works as intended.

**Comment by MrRaposinha** [comment]
@xMikux  Hey, another question: how did you pre-generate this pack without both conflicting? I'm just curious.

**Comment by xMikux** [comment]
Actually really simple, just put on the ``ItemsAdder/contents/``, and make it auto-merge custom model together.

https://itemsadder.devs.beer/plugin-usage/merge-resourcepacks

**Comment by xMikux** [comment]
so it won't contain two same custom model json, and conflicting.
