### ISSUE TITLE
Include Supreme Support

### ISSUE THREAD

**Issue by RelativoBR** [xMikux/Slimefun-Resourcepack#19]
**Describe about this feature request.**
I would like to ask if you could include the textures that exist for the supreme addon?

[texture_part_of_supreme.zip](https://github.com/xMikux/Slimefun-Resourcepack/files/10912203/texture_part_of_supreme.zip)

I don't know how to configure it but I have the images and the file names are the item IDs in Slimefun. This was part of an old texture that is not compatible.

**Comment by xMikux** [comment]
Yeah, sure. I can help you to include the texture!
Thanks for your contribution. ❤️ 

I will need some time to include these textures into the project.

**Comment by xMikux** [comment]
Hi, I add Supreme on https://github.com/xMikux/Slimefun-Resourcepack/commit/d561c330d4e8275ab96c31e533b36e7e1f8a3a66

Can you help me to check all textures apply correctly?
You can download [Beta Pack](https://github.com/xMikux/Slimefun-Resourcepack/releases/tag/latest-build) to test.

**Comment by xMikux** [comment]
Hello, do you confirm all texture work correctly? 
This issue will close as completed after one day.
