### ISSUE TITLE
IA armor

### ISSUE THREAD

**Issue by hankwu0501** [xMikux/Slimefun-Resourcepack#2]
使用IA的新功能

**Comment by xMikux** [comment]
補充 使用 IA Custom Armor Renderer

**Comment by xMikux** [comment]
在我進行研究過後 發現該功能僅能運用在皮革套裝
因為他正在使用特殊的皮革套裝顏色來達成
可能很難運用在此上面 所以將會繼續使用CIT的功能來達成
(或許我這個研究是錯誤的 但我並不確定)

**Comment by xMikux** [comment]
由於無法實現 所以此問題將會被關閉
目前我已經把Optifine整合再一起
並不會在分成兩個版本
