### ISSUE TITLE
Missing textures for magical_armor/slime_armor

### ISSUE THREAD

**Issue by Texbio** [xMikux/Slimefun-Resourcepack#20]
**Describe the problem:**

The armor has some spots where it is invisible which makes no sense cause there is currently no texture for it.
**Screenshots:**
One of the screenshots just has some edited textures, but still highlights the issue
<img width="252" alt="scr1" src="https://user-images.githubusercontent.com/36513888/224547978-abd8f23e-da78-4d38-9396-c512df38c1b3.png">
<img width="255" alt="scr2" src="https://user-images.githubusercontent.com/36513888/224547983-cf2f949c-9d2a-4001-a296-79417b4be104.png">

- Resourcepack Version:
-  [Beta Pack](https://github.com/xMikux/Slimefun-Resourcepack/releases/tag/latest-build)
- [v1.0.11](https://github.com/xMikux/Slimefun-Resourcepack/releases/tag/v1.0.11)

Version:
Minecraft Version: 1.19.3 Vanilla

Current Plugins:
ExcellentEnchants-3.3.1.jar
ItemsAdder_3.4.0c-beta.jar
LoneLibs.jar
MythicMobs-5.2.1.jar
NexEngine-2.2.9.jar
ProtocolLib-614.jar
sf_ColoredEnderChests - DEV 23 (git 4d041).jar
sf_DankTech2 - DEV 8 (git f2a8a).jar
sf_ExtraTools - DEV 36 (git 922c0).jar
sf_FluffyMachines - DEV 130 (git 01c83).jar
sf_InfinityExpansion - DEV 140 (git 0098d).jar
sf_MissileWarfare.v1.6.13.jar
sf_Networks - DEV 45 (git ade6f).jar
sf_SimpleMaterialGenerators - DEV 4 (git 5543c).jar
sf_SlimeHUD v1.2.7.jar
Slimefun4 - DEV 1047.jar
ViaBackwards-4.5.1.jar
ViaVersion-4.5.1.jar

I fixed this issue by adding my own textures images and models text files in:
assets\slimefun\models\slimefun\magical_armor\slime_armor
assets\slimefun\textures\slimefun\magical_armor\slime_armor

**Comment by xMikux** [comment]
Hi, because Slime Armors doesn't have their own texture, I tried to redirect Minecraft vanilla leather armor, but it seems not fixed.

**Comment by xMikux** [comment]
oh wait I know, it will be fixed later.

**Comment by xMikux** [comment]
![image](https://user-images.githubusercontent.com/26039249/224550838-43ddd3eb-ac59-4174-b6dc-9412be17fdbe.png)

It should fix on 2e6f161, can you confirm this fix?
