### ISSUE TITLE
Support for SlimefunWarfare

### ISSUE THREAD

**Issue by Filosofas154** [xMikux/Slimefun-Resourcepack#21]
Hey! As you said you are not an artist but I may be able to provide you with some textures. Wouldn't it be a problem for you to implement it? I already have some textures.

**Comment by xMikux** [comment]
Yeah, sure, I can implement it.
You can upload it here, or fork and pr the texture to the project, I can help you implement it, but please make sure the png file name is same as SlimefunWarfare Item ID, thanks!

**Comment by xMikux** [comment]
Thanks for your contribution! ❤️
It is okay you don't know about IDs, I just need some info about image, the latest name match should be fine.
I will need some time to implement it.

**Comment by Filosofas154** [comment]
No problem! Take your time! Thank you once again.

**Comment by xMikux** [comment]
Hi, I have implemented your textures on 84d9030.
Can you help me check all textures apply correctly?
You can download [Beta Pack](https://github.com/xMikux/Slimefun-Resourcepack/releases/tag/latest-build) to test it!

Also, I see there have two images ``multimeater.png`` ``portable_geo_scanner.png`` is not from SlimefunWarfare.

**Comment by Filosofas154** [comment]
Yes, everything works correctly! Thank you very much!

>  Also, I see there have two images multimeater.png portable_geo_scanner.png is not from SlimefunWarfare.
Yeah, I may have moved those textures by accident.
