### ISSUE TITLE
Replace the GUI backgrounds with stained glass to support other resourcepacks.

### ISSUE THREAD

**Issue by slash1div** [xMikux/Slimefun-Resourcepack#22]
**Describe about this feature request.**
Pretty simple. Just a replacement of the light gray backgrounds with transparency and gray stained glass.
Although the vanilla colored background tiles look nice without a resourcepack, they mess around with backgrounds.
I edited the pack for my server with this to add more support since it annoyed some people.
Most of my playerbase loves PVP, so it helped a lot with darkmode packs like VanillaPlus v2 to look less jarring.
Helps especially in the Settings and Info menus.

_**Before and after:**_
![image](https://user-images.githubusercontent.com/83387831/232176365-ee83b9e0-4d44-46ff-8e33-dc52dff7a782.png)

**Files I removed:**
`\assets\minecraft\models\item\gray_stained_glass_pane.json`
`\assets\slimefun\textures\slimefun\gui\pane_gray.png`

**Files I added transparency to:**
The `\assets\slimefun\textures\slimefun\gui\` directory; everything changed but `slimefun_guide.png`
This file I never really saw in-game, but I noticed in the slimefun folder `\assets\slimefun\textures\slimefun\none.png`

**Comment by xMikux** [comment]
Thanks for your suggestion! 

I will implement this later.

``assets/slimefun/textures/slimefun/none.png`` is for missing texture placeholder, I have all disabled, because I think is rarely someone contribute the missing texture.

**Comment by xMikux** [comment]
Hi, I have implemented this on ee62b2b, can you confirm it works as you request?
