### ISSUE TITLE
Licensing for this resoruce pack

### ISSUE THREAD

**Issue by mio9** [xMikux/Slimefun-Resourcepack#24]
**Describe about this feature request.**

What will be the licensing for this resourcepack? Since there is no LICENSE file in the repo, and we would like to let our server player use it conveniently by including this resourcepack as part of our custom modpack, we cannot do that without the acknowledgement from you the author.

**Comment by xMikux** [comment]
Hi, I don't know which license will be great for this pack, also some of textures are from the internet (like mods).

**Comment by mio9** [comment]
Hmm.. I guess we'll go for the build server approach then... anyways thanks for your answer and your hardwork in putting everything together. So far your resourcepack is the only one that's keep updating while not having things all over the place
