### ISSUE TITLE
材质包模型错误

### ISSUE THREAD

**Issue by 429349613** [xMikux/Slimefun-Resourcepack#27]
**描述问题**：服务器用IA加载的材质包，所有cube_all的方块都出问题了.
**MC版本**：1.20.1
**材质包版本**：最新
**截图**：
![image](https://github.com/xMikux/Slimefun-Resourcepack/assets/69417877/b291dbb4-9408-4d0e-86ba-38fc012daa11)

**Comment by xMikux** [comment]
你有裝任何模組嘛？

**Comment by 429349613** [comment]
确实是客户端mod的问题 正在排查

**Comment by 429349613** [comment]
> 你有裝任何模組嘛？

确实是客户端mod的问题 正在排查

**Comment by 429349613** [comment]
> > 你有裝任何模組嘛？
> 
> 确实是客户端mod的问题 正在排查
罪魁祸首是[OMMC]Oh My Minecraft Client模组
将它卸载就好了
[https://github.com/Nyan-Work/oh-my-minecraft-client/](url)
