### ISSUE TITLE
Re-name some files for ID consistency

### ISSUE THREAD

**Issue by JustAHuman-xD** [xMikux/Slimefun-Resourcepack#29]
**Describe the problem:**
I develop a mod called SlimefunEssentials, one of its features is adding slimefun items and recipes to jei, rei, and emi, a heavily requested feature was adding support for custom model data.

So I've been working on the feature and have got it nearly complete. The problem is that it detects the custom model data only if the model name is the same as the slimefun id. 

In the case of your resource pack that is only true part of the time. So I was wondering if you'd be up just to renaming the files, I can make the PR myself if you'd like. 

I also completely get it if you don't want to make that change so no problem regardless!

**Comment by JustAHuman-xD** [comment]
I selected the question label not bug label but it appears to have decided not to add that one lol

**Comment by xMikux** [comment]
Hi, welcome to PR this!
I don't mind something break, because I always break something :laughing:

**Comment by xMikux** [comment]
There is no report about ID rename issues, so it is safe to close this.

Thanks!
