### ISSUE TITLE
Armor CIT path can't locate on Optifine

### ISSUE THREAD

**Issue by Pizzalopa** [xMikux/Slimefun-Resourcepack#3]
**Describe the issue: Some armor textures don't show when equipped on the player**

Some armor textures don't show when equipped on the player

**Reproduction Steps:**

Just wear the armor

**Expected behavior:**

To not bug?

**Screenshots:**

![image](https://user-images.githubusercontent.com/93993071/159731007-a04e4ad9-3508-41ea-9fa3-2b4c7012c472.png) that's when wearing the cactus armor, and many others too

**Version Info:**

- Resourcepack Version:
- Minecraft Version:
  - [ ] 1.18
- Optifine Install
  - [ ] Installed

**Additional Info:**

Add other describe about this bug.

**Comment by xMikux** [comment]
Hi, what version do you use.

**Comment by xMikux** [comment]
I test on my beta pre release, it work normal

![image](https://user-images.githubusercontent.com/26039249/159772603-2fc9697b-1f2f-4323-8e17-40d49863d6d5.png)

**Comment by xMikux** [comment]
After I check the optifine, i notice the bug.
Look like it work normal on Fabric CIT Resewn
but not work on optifine
because I use optifine not support thing
![image](https://user-images.githubusercontent.com/26039249/159778955-19bef8e8-2e45-4901-9072-ba3f4f67496f.png)

**Comment by xMikux** [comment]
I will update the fix on Beta Pack tomorrow.

**Comment by Pizzalopa** [comment]
> I will update the fix on Beta Pack tomorrow.

alright, thank you, notify me, you should create a discord support server by the way

**Comment by xMikux** [comment]
At present, I don't plan to create a support Discord Server for this texture pack, but you can still join my slimefun translate Discord (Traditional Chinese). You can find me there directly for support.

**Comment by xMikux** [comment]
On this two commits 1e99733 7981443 should fix this issues, if you get any armor textures missing, pleases let me know.

Also, if you need to update to Beta Pack, there have a breaking change on it a55de43, need to update item-models.yml
