### ISSUE TITLE
安装OMMC模组，导致一些物品贴图错位

### ISSUE THREAD

**Issue by czszzh** [xMikux/Slimefun-Resourcepack#31]
**描述問題：**

客户端安装OMMC(Oh My Minecraft Client)模组，导致在粘液科技界面中一些物品贴图出现错位

**截圖：**
![屏幕截图 2024-06-09 013630](https://github.com/xMikux/Slimefun-Resourcepack/assets/138607354/21e90b79-f4b1-426b-b4b8-5038c436ab8f)
![屏幕截图 2024-06-09 013654](https://github.com/xMikux/Slimefun-Resourcepack/assets/138607354/19559e7a-194d-4a30-9ca7-3866ee18f38a)

**版本資訊：**
- 資源包版本：
  -v1.0.11
- Minecraft 版本：
  - 1.20.1
- CIT 模組：
  - CIT Resewn

**Comment by czszzh** [comment]
有个解决办法是去除OMMC模组

**Comment by xMikux** [comment]
對於模組的支援 我可能沒辦法修好
#27 就有過這問題

**Comment by xMikux** [comment]
我不確定是哪個功能造成的
你可以嘗試看看把下方圖片的功能關閉
![image](https://github.com/xMikux/Slimefun-Resourcepack/assets/26039249/0b516485-6ec7-4cd4-9015-2899d70bd9df)
