### ISSUE TITLE
厨师机器人的材质和至尊的速度属性SUPREME_ATTRIBUTE_IMPETUS混了

### ISSUE THREAD

**Issue by haiman233** [xMikux/Slimefun-Resourcepack#48]
厨师机器人的材质和至尊的速度属性SUPREME_ATTRIBUTE_IMPETUS混了
QWQ

**Comment by xMikux** [comment]
![image](https://github.com/user-attachments/assets/2ff85ee5-5909-4b2e-8a2c-833d81e424b4)
我重新檢查了一下，廚師機器人似乎沒有衝突?

**Comment by xMikux** [comment]
喔我找到了 原來在附加中 太久沒用了

**Comment by xMikux** [comment]
現在修好了，因為它被分配了 Model ID，但廚師機器人並未有材質才導致他會去混合到其他材質

很多時候都會發生這種情況，只要沒有材質情況下給他個 ID，然後又很剛好他的物品材料跟其他已有的材料符合就會套上了

**Comment by xMikux** [comment]
可以測試看看是否有修好
https://modrinth.com/resourcepack/slimefun-resourcepack/version/git-1d70950
