### ISSUE TITLE
已安装CIT Resewn模组，但盔甲材质在玩家身上不显示

### ISSUE THREAD

**Issue by XXY233** [xMikux/Slimefun-Resourcepack#51]
**描述問題：** 史莱姆套装的材质在 1.21.1 中不显示，疑似路径错误。资源包版本使用的v1.2.0

**截圖：**
![be25b533f749a4c551895a29ec1d99b2](https://github.com/user-attachments/assets/f90e5d72-8fa3-4e21-95b3-9baab833dc68)

**Comment by xMikux** [comment]
能貼一下未有材質的史萊姆套裝嗎 感謝

**Comment by XXY233** [comment]
![image](https://github.com/user-attachments/assets/9bb4b1af-fba2-43f1-9818-296cab4529de)

**Comment by xMikux** [comment]
我回家會檢查一下哪裡有問題

**Comment by xMikux** [comment]
啊等等

**Comment by xMikux** [comment]
我想起來了 史萊姆套裝目前沒材質

**Comment by xMikux** [comment]
如果你照著路徑去看我指定的 是原版皮革 model

**Comment by xMikux** [comment]
https://github.com/xMikux/Slimefun-Resourcepack/tree/main/Resourcepack/contents/slimefun/resourcepack/slimefun/models/slimefun/magical_armor/slime_armor

**Comment by XXY233** [comment]
啊，好吧。那为什么会有这些东西😱
![image](https://github.com/user-attachments/assets/4176bc75-ec04-4204-950c-eb0f9a0f6f07)

**Comment by xMikux** [comment]
那好像是鋼鐵史萊姆套裝 但我其實不知道為啥這存在

**Comment by xMikux** [comment]
喔 史萊姆套裝的升級版

**Comment by xMikux** [comment]
變得更硬邦邦

**Comment by XXY233** [comment]
哦，真不好意思，我搞错问题了可能。对不起，是我没有搞清楚问题，真的很抱歉，其实不存在这个问题。

**Comment by XXY233** [comment]
实在是抱歉哈！其实我想问的是另外一个问题，就是穿上之后，玩家身上的材质会不显示，这是BUG吗？
![image](https://github.com/user-attachments/assets/d517e319-2f17-4d8c-a7f2-938a454f182a)

**Comment by xMikux** [comment]
不算是 對於顯示盔甲外層的 原版其實辦不到
需要安裝 Cit Resewn
https://github.com/xMikux/Slimefun-Resourcepack/tree/docs/update-readme?tab=readme-ov-file#-recommand-mods
(目前 Readme 正在重寫中)

**Comment by XXY233** [comment]
嗷嗷！原来是这样，感谢您的解答，谢谢。明白了

**Comment by XXY233** [comment]
不对劲……我重新测试了一下，发现 1.21.1 中装了CIT Resewn也不会显示，但是 1.20.4 中是没问题的。
- 1.20.4: 
![image](https://github.com/user-attachments/assets/5e5910d3-ce84-492a-ba36-1cfddedf624e)
- 1.21.1: 
![image](https://github.com/user-attachments/assets/2f4b69a3-baf8-477a-bdc3-efd8b378a020)

**Comment by XXY233** [comment]
我的朋友新开了一个问题，去那里讨论吧：https://github.com/xMikux/Slimefun-Resourcepack/issues/52
