### ISSUE TITLE
盔甲cit材质在1.21未正确工作

### ISSUE THREAD

**Issue by jiajia06403** [xMikux/Slimefun-Resourcepack#52]
Minecraft版本1.20.1: 
![Screenshot_20240927_175146_edit_1708825080159174](https://github.com/user-attachments/assets/272d9cdf-7047-4601-891e-16001ec9bdbe)

Minecraft版本1.21.1:
![Screenshot_20240927_175600_edit_1708814798302720](https://github.com/user-attachments/assets/f5b01014-7273-4f25-8188-ff35e0eb2a4c)

客户端均安装了cit模组(1.20.1: cit模组1.1.5版本，1.21.1: cit模组1.2.1版本)

**Comment by xMikux** [comment]
好，我剛花了一些時間研究一下這問題，我注意到 CIT 在最新版本 1.21 的判斷格式改變了

```diff
- nbt.CustomModelData=2200076
+ components.custom_model_data=2200076
```

若我對這個進行更新的話，會導致 1.21 以下的 CIT 都不會顯示

**Comment by jiajia06403** [comment]
好奇如果同时写这两种会怎么样

**Comment by xMikux** [comment]
兩個都不會作用

**Comment by jiajia06403** [comment]
什么时候更新呢qwq，出两个release呗

**Comment by xMikux** [comment]
有空的時候我會想想看要怎麼做
