### ISSUE TITLE
无尽拓展动态材质的问题

### ISSUE THREAD

**Issue by jiajia06403** [xMikux/Slimefun-Resourcepack#53]
无尽催化剂/无尽锭之类的动态材质，正常应该是饱和度越来越低然后越来越高，现在却是越来越低之后瞬间复位到正常饱和度。。。
正常的样子↓
![36450](https://github.com/user-attachments/assets/48d52313-cf49-481f-9a5c-e5e5e69690c7)

尝试通过在材质对应mcmeta中添加Frames:[0,1,2,3,4,5,6,7,8,7,6,5,4,3,2,1,0] （无尽催化剂有9frames）出现了紫黑方块。。。不过大概就是需要加这个玩意

**Comment by xMikux** [comment]
可以的話 能直接 PR

**Comment by jiajia06403** [comment]
很抱歉，正如我描述的，我尝试修改出现了紫黑方块的丢失材质问题。。。不是很会搞这个

**Comment by jiajia06403** [comment]
我试试

**Comment by xMikux** [comment]
感謝貢獻修正，你可以在測試版測試此問題是否還存在

https://modrinth.com/resourcepack/slimefun-resourcepack/version/git-9310bb4

**Comment by jiajia06403** [comment]
oh no，最新版本似乎把这个修复给回退了

**Comment by jiajia06403** [comment]
无尽套的动态材质还是不对
