### ISSUE TITLE
启用资源包后木头的放置和破坏会没有声音

### ISSUE THREAD

**Issue by XXY233** [xMikux/Slimefun-Resourcepack#54]
客户端版本：1.21
资源包版本：v1.2.0

- 未启用资源包的截图
![image](https://github.com/user-attachments/assets/7029a142-5d30-45cc-aeaa-b33399cbef73)
![image](https://github.com/user-attachments/assets/d5d18051-f7fd-4fd0-a455-8b841f5e185a)

- 启用资源包后的截图：
![image](https://github.com/user-attachments/assets/ab08a755-1a85-434c-858e-d6a2498b19a1)
![image](https://github.com/user-attachments/assets/e248cc02-b663-46fd-85f4-ec79c86210ba)

**Comment by xMikux** [comment]
此問題已修正，你可以在測試版上測試看看該問題是否存在

https://modrinth.com/resourcepack/slimefun-resourcepack/version/git-716628d

**Comment by XXY233** [comment]
确认已修正，谢谢！
