### ISSUE TITLE
铒锭和至尊粒的奇怪透明部分

### ISSUE THREAD

**Issue by jiajia06403** [xMikux/Slimefun-Resourcepack#55]
erbium_ingot:
![erbium_ingot](https://github.com/user-attachments/assets/c96b08c9-9377-44db-b70c-acbe68cf21dc)

supreme_nugget:
![supreme_supreme_nugget](https://github.com/user-attachments/assets/68849e27-9fc9-4154-beb9-f8f5e6c08e9a)

两者都有很突兀的中间的透明部分

**Comment by jiajia06403** [comment]
这怎么说，能补一下吗

**Comment by xMikux** [comment]
一樣需要原始作者或有人幫助修復 不然也只能先暫時這樣

**Comment by AlmostPanda** [comment]
I can look at it later if you want, busy rn
