### ISSUE TITLE
缺失至尊套的cit材质

### ISSUE THREAD

**Issue by jiajia06403** [xMikux/Slimefun-Resourcepack#57]
如题

**Comment by xMikux** [comment]
該附加並未有 CIT 材質
需要有人幫助

**Comment by AlmostPanda** [comment]
I noticed this issue and had around 30mins of free time so I made the cit texture.
If you like it, I can send it for implementation
![image](https://github.com/user-attachments/assets/bce2d56b-1d97-42ab-a949-342cccbfc6d7)
