### ISSUE TITLE
焦糖的材质错误的显示成了红石合金锭

### ISSUE THREAD

**Issue by BerryMC** [xMikux/Slimefun-Resourcepack#92]
- 焦糖的材质错误的显示成了红石合金锭

![image](https://github.com/user-attachments/assets/7c31e6b1-91bd-4579-881b-f7b9b5f8f868)

- 资源包版本：最新
- Minecraft 版本：1.20.6
- CIT 模組：CIT Resewn
（哦天哪，这块焦糖真硬）

**Comment by xMikux** [comment]
~~其實我一直以為那是正確的材質~~
找時間把他換回原版磚頭
這個焦糖應該是無材質的

**Comment by xMikux** [comment]
已經在 PR 94 中修復 你可以測試看看有沒有修好
https://modrinth.com/resourcepack/slimefun-resourcepack/version/git-5babaec
